### ISSUE TITLE
Chunked - GAME BREAKING BUG

### ISSUE THREAD

**Issue by iStrykr** [iStrykr/Natronic#9]
There was a winner and no ending, and there is a buggy glitch of a hidden glass layer.

Grasslands is apparently is buggy map.

**Comment by iStrykr** [comment]
There is 1 player left in the game after killing all in deathmatch but the game doesn't end, unless all log off.

**Comment by barcedev** [comment]
Issues resolved. Due to the new death system, I forgot to implement the new way for the game to end. _Oops_.

Thanks for reporting.
